export const FETCH_POSTS = "FETCH_POSTS";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const FETCH_POST_DETAILS = "FETCH_POST_DETAILS";
export const FETCH_POST_DETAILS_WITH_CONTENT_TYPE = "FETCH_POST_DETAILS";
