export const LIST_NOTIFICATIONS    =   "LIST_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS   =   "FETCH_NOTIFICATIONS";
export const PATCH_NOTIFICATIONS   =   "PATCH_NOTIFICATIONS";
export const UPDATE_NOTIFICATIONS  =   "UPDATE_NOTIFICATIONS";
