export const CREATE_REVENUE_SPLIT = "CREATE_REVENUE_SPLIT";
export const FETCH_REVENUE_SPLITS = "FETCH_REVENUE_SPLITS";
export const UPDATE_REVENUE_SPLIT = "UPDATE_REVENUE_SPLIT";
export const DELETE_REVENUE_SPLIT = "DELETE_REVENUE_SPLIT";
